apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindie-motor-kv-store
  labels:
    app: mindie-motor-kv-store
  namespace: mindie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindie-motor-kv-store
  template:
    metadata:
      labels:
        app: mindie-motor-kv-store
        deploy-name: mindie-motor-kv-store
    spec:
      terminationGracePeriodSeconds: 0
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1001
      containers:
        - image: mindie:1.0.0-aarch64-800I-A2
          imagePullPolicy: IfNotPresent
          name: mindie-motor-kv-store
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: Unconfined
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONFIGMAP_PATH
              value: /mnt/configmap
            - name: CONFIG_PATH
              value: /usr/local/Ascend/pyMotor/conf
            - name: ROLE
              value: kv_store
          command: ["/bin/bash", "-c", "source /mnt/configmap/boot.sh;"]
          resources:
            requests:
              memory: "2Gi"
              cpu: "4"
            limits:
              memory: "4Gi"
              cpu: "8"
          volumeMounts:
            - name: motor-config
              mountPath: /mnt/configmap
            - name: mnt
              mountPath: /mnt
            - name: coredump
              mountPath: /var/coredump
            - name: ascend-driver
              mountPath: /usr/local/Ascend/driver
            - name: driver
              mountPath: /driver
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: motor-config
          configMap:
            name: motor-config
            defaultMode: 0550
        - name: mnt
          hostPath:
            path: /mnt
        - name: coredump
          hostPath:
            path: /var/coredump
            type: DirectoryOrCreate
        - name: ascend-driver
          hostPath:
            path: /usr/local/Ascend/driver
        - name: driver
          hostPath:
            path: /driver
        - name: varlog
          hostPath:
            path: /var/log
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mindie-motor-kv-store
  name: mindie-motor-kvs-master
  namespace: mindie
spec:
  ports:
  - name: business
    port: 50088
    protocol: TCP
    targetPort: 50088
  - name: config-store
    port: 50089
    protocol: TCP
    targetPort: 50089
  - name: metrics
    port: 50090
    protocol: TCP
    targetPort: 50090
  selector:
    app: mindie-motor-kv-store
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
